### ISSUE TITLE
Error: skip not supported yet

### ISSUE THREAD

**Issue by whitehander** [omnisci/mapd-connector#101]
Other query(select..) is works fine, but INSERT query is occur error

`"INSERT INTO test VALUES ('2018-08-23T13:00:00+09:00', '[{"type":"elec","value":1},{"type":"elec2","value":1}]');"`

`Error: skip not supported yet
    at TJSONProtocol.module.exports.TJSONProtocol.skip (mapd-connector/dist/node-connector.js:7073:10)
    at module.exports.module.exports.TColumnType.module.exports.TColumnType.read (mapd-connector/dist/node-connector.js:11046:16)
    at module.exports.module.exports.TRowSet.module.exports.TRowSet.read (mapd-connector/dist/node-connector.js:11677:21)
    at module.exports.module.exports.TQueryResult.module.exports.TQueryResult.read (mapd-connector/dist/node-connector.js:11824:25)
    at MapD_sql_execute_result.module.exports.MapD_sql_execute_result.read (mapd-connector/dist/node-connector.js:17949:25)
    at module.exports.exports.Client.module.exports.MapDClient.recv_sql_execute (mapd-connector/dist/node-connector.js:25489:11)
    at decodeCallback (mapd-connector/dist/node-connector.js:1999:42)
    at mapd-connector/dist/node-connector.js:800:6
    at IncomingMessage.<anonymous> (mapd-connector/dist/node-connector.js:2051:47)
    at IncomingMessage.emit (events.js:187:15)`

**Comment by whitehander** [comment]
I solved problem myself, But it is temporarily solution.

I changed code dist/node-connector.js:7073

TJSONProtocol.prototype.skip = function(type) {
	  throw new Error('skip not supported yet');
};

=>

	TJSONProtocol.prototype.skip = function(type) {
	  switch (type) {
	    case Type.STOP:
	      return;
	    case Type.BOOL:
	      this.readBool();
	      break;
	    case Type.BYTE:
	      this.readByte();
	      break;
	    case Type.I16:
	      this.readI16();
	      break;
	    case Type.I32:
	      this.readI32();
	      break;
	    case Type.I64:
	      this.readI64();
	      break;
	    case Type.DOUBLE:
	      this.readDouble();
	      break;
	    case Type.STRING:
	      this.readString();
	      break;
	    case Type.STRUCT:
	      this.readStructBegin();
	      while (true) {
	        var r = this.readFieldBegin();
	        if (r.ftype === Type.STOP) {
	          break;
	        }
	        this.skip(r.ftype);
	        this.readFieldEnd();
	      }
	      this.readStructEnd();
	      break;
	    case Type.MAP:
	      var mapBegin = this.readMapBegin();
	      for (var i = 0; i < mapBegin.size; ++i) {
	        this.skip(mapBegin.ktype);
	        this.skip(mapBegin.vtype);
	      }
	      this.readMapEnd();
	      break;
	    case Type.SET:
	      var setBegin = this.readSetBegin();
	      for (var i2 = 0; i2 < setBegin.size; ++i2) {
	        this.skip(setBegin.etype);
	      }
	      this.readSetEnd();
	      break;
	    case Type.LIST:
	      var listBegin = this.readListBegin();
	      for (var i3 = 0; i3 < listBegin.size; ++i3) {
	        this.skip(listBegin.etype);
	      }
	      this.readListEnd();
	      break;
	    default:
	      throw new Error("Invalid type: " + type);
	  }
};

**Comment by jrajav** [comment]
This instance of this issue should be fixed by now, but it has re-manifested recently. Tracking at https://github.com/omnisci/mapd-connector/issues/135
