### ISSUE TITLE
can't connect omnisci db exception

### ISSUE THREAD

**Issue by vqalex** [omnisci/mapd-connector#196]
## :beetle: If bug
  - [ubuntu 18.04 ] Operating System and version:
  - [ ] Browser and version:
  - [defaul setup const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "admin"
const password = process.env.PASSWORD || "HyperInteractive" ] Steps to reproduce (including dashboard link):
  - [trying to connect to DB and always getting with default installation, creds are default: Something bad happened:  { TOmniSciException: TOmniSciException
    at OmniSci_connect_result.module.exports.OmniSci_connect_result.read (/home/home/node_modules/@mapd/connector/dist/node-connector.js:20380:2257)
    at module.exports.exports.Client.module.exports.OmniSciClient.recv_connect (/home/home/node_modules/@mapd/connector/dist/node-connector.js:20380:240831)
    at decodeCallback (/home/home/node_modules/@mapd/connector/dist/node-connector.js:3432:42)
    at /home/home/node_modules/@mapd/connector/dist/node-connector.js:964:6
    at IncomingMessage.<anonymous> (/home/home/node_modules/@mapd/connector/dist/node-connector.js:3488:47)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'TOmniSciException',
  message: 'TOmniSciException',
  error_msg: 'Authentication failure' }
 ] Description of issue:

## :new: If feature request  
  - [ ] User story:
  - [ ] Specific requirements/functionality:
  - [ ] Mocks (if applicable):

**Comment by vqalex** [comment]
this is what is in the logs

omnisci_server[1144]: 2020-09-14T11:02:28.552896 E 1144 16 DBHandler.cpp:548 Authentication failure

default creds are used 

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "omnisci"
const password = process.env.PASSWORD || "HyperInteractive"

tried

const hostname = process.env.HOSTNAME || "localhost"
const protocol = process.env.PROTOCOL || "http"
const port = process.env.PORT || "6273"
const database = process.env.DATABASE || "omnisci"
const username = process.env.USERNAME || "admini"
const password = process.env.PASSWORD || "HyperInteractive"

the same problem
omnisci_server[1144]: 2020-09-14T11:02:28.552896 E 1144 16 DBHandler.cpp:548 Authentication failure
